<?php include "common/header.php" ?>


    
    <div class="container-fluid header-bg py-5 mb-5 wow fadeIn" data-wow-delay="0.1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeIn;">
      <div class="container py-5">
        <h1 class="display-4 text-white mb-3  slideInDown">Cookie Policy</h1>
        <nav aria-label="breadcrumb animated slideInDown">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">
              <a class="text-white" href="index.php">Home</a>
            </li>
            <li class="breadcrumb-item text-primary active" aria-current="page">
              Cookie Policy
            </li>
          </ol>
        </nav>
      </div>
    </div>
    <!--breadcrumb close here-->
    
    
    <div class="container py-5">
        <div class="WordSection1">
  <h1>Cookie Policy</h1>


  <p class="MsoBodyText">Updated at 2022-07-12</p>

  <p class="MsoBodyText"><span>&nbsp;</span></p>

  <p class="MsoBodyText">&nbsp;</p>

  <h1>Definitions and key terms</h1>


  <p
    class="MsoBodyText"
  >
    To help explain things as clearly as possible in this Cookie Policy, every
    time any of these terms are referenced, are strictly<span
    >
    </span
    >defined as:
  </p>

  <p class="MsoBodyText">
    <span>&nbsp;</span>
  </p>

  <p
    class="MsoListParagraph"
  >
    <span>·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >Cookie: small amount of data generated by a website and saved by your web
      browser. It is used to identify your browser,<span
      >
      </span
      >provide analytics, remember information about you such as your language
      preference or login information.</span
    >
  </p>

  <p class="MsoListParagraph">
    <span>·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >Company: when this policy mentions “Company,” “we,” “us,” or “our,” it
      refers to Vensemart, that is responsible for your</span
    >
  </p>

  <p
    class="MsoBodyText"
  >
    <span
      >·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span
    >information under this Cookie Policy.
  </p>

  <p class="MsoListParagraph">
    <span>·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >Device: any internet connected device such as a phone, tablet, computer
      or any other device that can be used to visit</span
    >
  </p>

  <p
    class="MsoBodyText"
  >
    <span
      >·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span
    >Vensemart and use the services.
  </p>

  <p class="MsoListParagraph">
    <span>·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >Personal Data: any information that directly, indirectly, or in
      connection with other information — including a personal</span
    >
  </p>

  <p class="MsoBodyText">
    <span
      >·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span
    >identification number — allows for the identification or identifiability of
    a natural person.
  </p>

  <p class="MsoListParagraph">
    <span>·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >Service: refers to the service provided by Vensemart as described in the
      relative terms (if available) and on this platform.</span
    >
  </p>

  <p class="MsoListParagraph">
    <span>·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >Third-party service: refers to advertisers, contest sponsors, promotional
      and marketing partners, and others who provide</span
    >
  </p>

  <p
    class="MsoBodyText"
  >
    <span
      >·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span
    >our content or whose products or services we think may interest you.
  </p>

  <p class="MsoListParagraph">
    <span>·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >Website: Vensemart."’s" site, which can be accessed via this URL: </span
    ><a href="http://www.vensemart.com/"><span>www.vensemart.com</span></a>
  </p>

  <p class="MsoListParagraph">
    <span>·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >You: a person or entity that is registered with Vensemart to use the
      Services.</span
    >
  </p>

  <p class="MsoBodyText"><span>&nbsp;</span></p>

  <p class="MsoBodyText"><span>&nbsp;</span></p>

  <h1>Introduction</h1>


  <p class="MsoBodyText">
    This Cookie Policy explains how Vensemart and its affiliates (collectively
    "Vensemart", "we", "us", and "ours"), use cookies and<span
    
    >
    </span
    >similar technologies to recognize you when you visit our website/app,
    including without limitation
    <a href="http://www.vensemart.com/"
      ><span
        >www.vensemart.com</span
      ></a
    >
    and any<span> </span>related URLs, mobile or
    localized versions and related domains / sub-domains ("Websites"). It
    explains what these technologies<sp>
    </span
    >are and why we use them, as well as the choices for how to control them.
  </p>

  <p class="MsoBodyText"><span>&nbsp;</span></p>

  <h1>What is a cookie?</h1>


  <p class="MsoBodyText">
    A cookie is a small text file that is stored on your computer or other
    internet connected device in order to identify your browser,<span
    >
    </span
    >provide analytics, remember information about you such as your language
    preference or login information. They're completely<span
    >
    </span
    >safe and can't be used to run programs or deliver viruses to your device.
  </p>

  <p class="MsoBodyText"><span>&nbsp;</span></p>

  <h1>Why do we use cookies?</h1>


  <p class="MsoBodyText">
    We use first party and/or third party cookies on our website/app for various
    purposes such as:
  </p>

  <p class="MsoBodyText">
    <span>&nbsp;</span>
  </p>

  <p class="MsoListParagraph">
    <span>·<span>&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >To facilitate the operation and functionality of our website/app;</span
    >
  </p>

  <p class="MsoListParagraph">
    <span
      >·<span>&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >To improve your experience of our website/app and make navigating around
      them quicker and easier;</span
    >
  </p>

  <p class="MsoListParagraph">
    <span
      >·<span>&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >To allow us to make a bespoke user experience for you and for us to
      understand what is useful or of interest to you;</span
    >
  </p>

  <p class="MsoListParagraph">
    <span
      >·<span>&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >To analyze how our website/app is used and how best we can customize
      it;</span
    >
  </p>

  <p class="MsoListParagraph">
    <span
      >·<span>&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >To identify future prospects and personalize marketing and sales
      interactions with it;</span
    >
  </p>

  <p class="MsoListParagraph">
    <span
      >·<span>&nbsp;&nbsp;&nbsp; </span></span
    ><span
      >To facilitate the tailoring of online advertising to your
      interests.</span
    >
  </p>

  <p class="MsoBodyText"><span>&nbsp;</span></p>

  <p class="MsoBodyText">
    <span>&nbsp;</span>
  </p>

  <h1>What type of cookies does Vensemart use?</h1>
</div>

    </div>
    
    
    

<?php include "common/footer.php" ?>