<?php include "common/header.php" ?>


    
    <div class="container-fluid header-bg py-5 mb-5 wow fadeIn" data-wow-delay="0.1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeIn;">
      <div class="container py-5">
        <h1 class="display-4 text-white mb-3  slideInDown">Privacy Policy</h1>
        <nav aria-label="breadcrumb animated slideInDown">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">
              <a class="text-white" href="index.php">Home</a>
            </li>
            <li class="breadcrumb-item text-primary active" aria-current="page">
              Privacy Policy
            </li>
          </ol>
        </nav>
      </div>
    </div>
    <!--breadcrumb close here-->
    
    
    <div class="container py-5">
        <div class="WordSection1">

<h1 style="margin-top:.05in">Privacy Policy</h1>


<p class="MsoBodyText" style="margin-left:5.15pt">Updated at 2022-07-12</p>


<p class="MsoBodyText" style="margin-top:9.85pt;margin-right:49.15pt;margin-bottom:
0in;margin-left:5.15pt;margin-bottom:.0001pt;line-height:121%">Vensemart (“we,”
“our,” or “us”) is committed to protecting your privacy. This Privacy Policy
explains how your personal information is collected, used, and disclosed by
Vensemart .</p>


<p class="MsoBodyText" style="margin-top:7.3pt;margin-right:7.9pt;margin-bottom:
0in;margin-left:5.15pt;margin-bottom:.0001pt;line-height:121%">This Privacy
Policy applies to our website, and its associated subdomains (collectively, our
“Service”) alongside our application, Vensemart . By accessing or using our
Service, you signify that you have read, understood, and agree to our
collection, storage, use, and disclosure of your personal information as
described in this Privacy Policy and our Terms of Service.</p>


<h1>Definitions and key terms</h1>


<p class="MsoBodyText" >To help explain
things as clearly as possible in this Privacy Policy, every time any of these
terms are referenced, are strictly defined as:</p>


<p class="MsoListParagraph" >
    <span >l<span > </span></span>
    <span >
        Cookie: small amount of data generated by a website and saved by your
        web browser. It is used to identify your browser, provide analytics, remember
        information about you such as your language preference or login information.
    </span>
</p>

<p class="MsoListParagraph"><span>l<span> </span></span><span>Company: when this policy mentions “Company,” “we,”
“us,” or “our,” it refers to Vensemart Apps Nigeria, O’Neal Center,</span></p>

<p class="MsoBodyText">plot 360
Obafemi Awolowo way, Jabi, Abuja that is responsible for your information under
this Privacy Policy.</p>

<p class="MsoListParagraph"><span>l<span> </span></span><span>Country: where Vensemart or the owners/founders of
Vensemart are based, in this case is Nigeria</span></p>

<p class="MsoListParagraph" ><span >l<span > </span></span><span style="font-size:
10.0pt">Customer: refers to the company, organization or person that signs up
to use the Vensemart Service to manage the</span></p>

<p class="MsoBodyText">relationships
with your consumers or service users.</p>

<p class="MsoListParagraph" ><span >l<span > </span></span><span >Device: any internet connected device such as a phone, tablet, computer
or any other device that can be used to visit</span></p>

<p class="MsoBodyText" >Vensemart
and use the services.</p>

<p class="MsoListParagraph"><span>l<span > </span></span><span >IP address: Every device connected to
the Internet is assigned a number known as an Internet protocol (IP) address.
These numbers are usually assigned in geographic blocks. An IP address can
often be used to identify the location<span > </span><span>from</span></span></p>

<p class="MsoBodyText">which a
device is connecting to the Internet.</p>

<p class="MsoListParagraph" ><span>l<span > </span></span><span>Personnel: refers to those individuals who are employed by Vensemart or
are under contract to perform a service on behalf</span></p>

<p class="MsoBodyText">of one of
the parties.</p>

<p class="MsoListParagraph" ><span >l<span > </span></span><span >Personal Data: any information that directly, indirectly, or in
connection with other information — including a personal</span></p>

<p class="MsoBodyText">identification
number — allows for the identification or identifiability of a natural person.</p>

<p class="MsoListParagraph"><span>l<span > </span></span><span>Service: refers to the service provided by Vensemart
as described in the relative terms (if available) and on this platform.</span></p>

<p class="MsoListParagraph" ><span >l<span > </span></span><span >Third-party service: refers to advertisers, contest sponsors,
promotional and marketing partners, and others who provide</span></p>

<p class="MsoBodyText" >our content
or whose products or services we think may interest you.</p>

<p class="MsoListParagraph"><span>l<span > </span></span><a href="http://www.vensemart.com/"><span>Website: Vensemart 's site, which can be accessed via
this URL: www.vensemart.com</span></a></p>

<p class="MsoListParagraph" ><span>l<span > </span></span><span >You: a person or entity that is registered with Vensemart to use the
Services.</span></p>

<h1>What Information Do We Collect?</h1>

<p class="MsoBodyText" ><b><span>&nbsp;</span></b></p>

<p class="MsoBodyText">We collect
information from you when you visit our website/app, register on our site,
place an order, subscribe to our newsletter, respond to a survey or fill out a
form.</p>


<p class="MsoListParagraph" ><span >l<span > </span></span><span>Name / Username</span></p>

<p class="MsoListParagraph"><span >l<span > </span></span><span>Phone Numbers</span></p>

<p class="MsoListParagraph"><span>l<span > </span></span><span>Email Addresses</span></p>

<p class="MsoListParagraph"><span >l<span > </span></span><span>Mailing Addresses</span></p>

<p class="MsoListParagraph"><span
>l<span > </span></span><span >Job Titles</span></p>

<p class="MsoListParagraph"><span >l<span > </span></span><span >Billing Addresses</span></p>

<p class="MsoListParagraph"><span>l<span > </span></span><span >Debit/credit card numbers</span></p>

<p class="MsoListParagraph"><span>l<span > </span></span><span >Age</span></p>

<p class="MsoListParagraph" ><span>l<span > </span></span><span>Password</span></p>

</div>
    </div>
    
    
    

<?php include "common/footer.php" ?>